# -------------------------------------------------------------------------------------
#
#    Config file for gene expression in dev human brain study - 110121 cell type IDs
#
# -------------------------------------------------------------------------------------


# ------   CELL RANGER  ------

SAMPLES_RNA:
#    14510_Cerebellum_B2_RNA:
#    14510_Hippocampus_B2_RNA:
#    14510_Thalamus_B2_RNA:
#    14611_Cerebellum_B2_RNA:
#    14611_Hippocampus_B2_RNA:
#    14611_Thalamus_B2_RNA:
#    14993_Cerebellum_B2_RNA:
#    14993_Hippocampus_B2_RNA:
#    14993_PFC_B2_RNA:
#    14993_Thalamus_B2_RNA:
#    14993_WGE_B2_RNA:
    14510_Cerebellum_B1_RNA:
#    14510_PFC_B1_RNA: 
    14510_Thalamus_B1_RNA:
#    14510_WGE_B1_RNA:
    14611_Cerebellum_B1_RNA:
#    14611_PFC_B1_RNA:
    14611_Thalamus_B1_RNA:
#    14611_WGE_B1_RNA:
    14993_Cerebellum_B1_RNA:
    14993_Thalamus_B1_RNA:
    14993_WGE_B1_RNA:

FASTQ_DIR: ../resources/fq
REFERENCE_RNA: /scratch/c.c1477909/cellRanger/refdata-gex-GRCh38-2020-A

# ---------  MAGMA  ----------

RNA_REGIONS:
    cer:
    hip:
    pfc:
    tha:
    wge:

SUMSTATS:
#    ADHD: GWAS_sumstats/GWAS_sumstats_RAW/demontis-walters-martin-2017-eur-adhd-summaryqc.tsv
#    ASD: GWAS_sumstats/GWAS_sumstats_RAW/grove-ripke-als-2017-eur-asd-summaryqc.tsv
#    BPD: GWAS_sumstats/GWAS_sumstats_RAW/daner_bip_pgc3_nm.tsv
#    MDD: GWAS_sumstats/GWAS_sumstats_RAW/wray-ripke-mattheisen-2017-mdd-23me-summaryqc.tsv
    SCZ: GWAS_sumstats/GWAS_sumstats_RAW/PGC3_SCZ_wave3_public.v2.tsv
    HEIGHT: GWAS_sumstats/GWAS_sumstats_RAW/Meta-analysis_Wood_et_al+UKBiobank_2018.txt
#    INTELLEGENCE: GWAS_sumstats/GWAS_sumstats_RAW/SavageJansen_2018_intelligence_metaanalysis.txt


# ---------  LDSC  ---------

RNA_CELL_TYPES:
    Cer-InN-1:
    Cer-RG-1:
    Cer-RG-2:
    Cer-ExN-1:
    Cer-InN-2:
    Cer-InN-3:
    Cer-InN-5:
    Cer-IP:
    Cer-ExN-2:
    Cer-RG-3:
    Cer-ExN-3:
    Cer-ExN-4:
    Cer-CycPro:
    Cer-InN-6:
    Cer-InN-4:
    Cer-InN-7:
    Cer-OPC:
    Cer-ExN-5:
    Cer-InN-8:
    Cer-Endo:
    Cer-MG:
    Hipp-ExN-1:
    Hipp-CR-1:
    Hipp-RG-1:
    Hipp-RG-2:
    Hipp-ExN-2:
    Hipp-InN-1:
    Hipp-ExN-3:
    Hipp-InN-2:
    Hipp-CycPro:
    Hipp-InN-3:
    Hipp-InN-3:
    Hipp-CR-2:
    Hipp-ExN-4:
    Hipp-ExN-5:
    Hipp-RG-3:
    Hipp-InN-4:
    Hipp-OPC:
    Hipp-ExN-6:
    Hipp-MG:
    Hipp-Endo:
    FC-ExN-1:
    FC-ExN-2:
    FC-ExN-3:
    FC-RG-1:
    FC-ExN-4:
    FC-InN-1:
    FC-InN-2:
    FC-ExN-5:
    FC-CycPro:
    FC-IP:
    FC-InN-3:
    FC-N-undef:
    FC-RG-2:
    FC-InN-4:
    FC-Endo:
    FC-OPC:
    FC-MG:
    Thal-RG-6:
    Thal-InN-1:
    Thal-RG-1:
    Thal-InN-2:
    Thal-InN-3:
    Thal-RG-2:
    Thal-InN-5:
    Thal-InN-6:
    Thal-ExN-1:
    Thal-CycPro:
    Thal-RG-7:
    Thal-IP:
    Thal-RG-3:
    Thal-InN-4:
    Thal-RG-4:
    Thal-InN-7:
    Thal-OPC:
    Thal-RG-5:
    Thal-ExN-2:
    Thal-ExN-3:
    Thal-InN-8:
    Thal-MG:
    Thal-Endo:
    GE-InN-1:
    GE-InN-2:
    GE-InN-3:
    GE-InN-4:
    GE-InN-5:
    GE-RG-1:
    GE-RG-2:
    GE-CycPro:
    GE-InN-6:
    GE-RG-3:
    GE-InN-7:

SIG_CELL_TYPES:
    FC-ExN-2:
    FC-ExN-3:
    FC-ExN-4: 
    FC-ExN-5: 
    FC-InN-1: 
    FC-InN-4:
    GE-InN-1: 
    GE-InN-2: 
    Hipp-ExN-3: 
    Hipp-ExN-5:
    Thal-ExN-1:
    Thal-ExN-3:

MAGMA_CONDITIONS:
    FC_ExN_2:    
    skene_InN:
    skene_MSN:
    skene_CA1: 
    skene_SS:
